app_package/authentication/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, BooleanField, SubmitField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from app_package.models import *




class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    name = StringField('Full Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    role = RadioField('Role', choices=[('Trainee','Trainee'),('Tutor','Tutor')],default='Trainee',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

app_package/authentication/__init__.py
from flask import Blueprint

bp = Blueprint("authentication", __name__)

from app_package.authentication import forms, routes

app_package/authentication/routes.py
from flask import request, render_template, flash, redirect, url_for
from app_package import app, db
from flask_login import current_user, login_user, logout_user, login_required
from app_package.models import (
    User,
    Courses,
    Chapters,
    Videos,
    subscriptions_table,
    completion_table,
)
from app_package.authentication.forms import LoginForm, RegistrationForm
from werkzeug.urls import url_parse
from app_package.authentication import bp


@bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("authentication.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("index")
        return redirect(next_page)
    return render_template("authentication/login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            username=form.username.data,
            email=form.email.data,
            role=form.role.data,
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Congratulations, you are now a registered user!")
        return redirect(url_for("authentication.login"))
    return render_template("authentication/register.html", title="Register", form=form)

app_package/templates/authentication/login.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('authentication.register') }}">Click to Register!</a></p>
{% endblock %}

app_package/templates/authentication/register.html
{% extends "base.html" %} {% block app_content %}
<h1>Register</h1>
<form action="" method="post">
  {{ form.hidden_tag() }}
  <p>
    {{ form.name.label }}<br />
    {{ form.name(size=32) }}<br />
    {% for error in form.name.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.username.label }}<br />
    {{ form.username(size=32) }}<br />
    {% for error in form.username.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.email.label }}<br />
    {{ form.email(size=32) }}<br />
    {% for error in form.email.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.role.label }}<br />
    {{ form.role }}<br />
    {% for error in form.role.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password.label }}<br />
    {{ form.password(size=32) }}<br />
    {% for error in form.password.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password2.label }}<br />
    {{ form.password2(size=32) }}<br />
    {% for error in form.password2.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>{{ form.submit() }}</p>
</form>
{% endblock %}